package BatalhaNaval;

import java.util.Scanner;

public class BatalhaNaval {
    static void mostraMapa(){
        String[][] mapa = new String[11][11];
        mapa[0][0] = " ";
        //linha
        mapa[0][1] = "A";
        mapa[0][2] = "B";
        mapa[0][3] = "C";
        mapa[0][4] = "D";
        mapa[0][5] = "E";
        mapa[0][6] = "F";
        mapa[0][7] = "G";
        mapa[0][8] = "H";
        mapa[0][9] = "I";
        mapa[0][10] = "J";
        //coluna
        mapa[1][0] = "0";
        mapa[2][0] = "1";
        mapa[3][0] = "2";
        mapa[4][0] = "3";
        mapa[5][0] = "4";
        mapa[6][0] = "5";
        mapa[7][0] = "6";
        mapa[8][0] = "7";
        mapa[9][0] = "8";
        mapa[10][0] = "9";
        //resto
        mapa[1][1] = "~";
        mapa[1][2] = "~";
        mapa[1][3] = "~";
        mapa[1][4] = "~";
        mapa[1][5] = "~";
        mapa[1][6] = "~";
        mapa[1][7] = "~";
        mapa[1][8] = "~";
        mapa[1][9] = "~";
        mapa[1][10] = "~";
        mapa[2][1] = "~";
        mapa[2][2] = "~";
        mapa[2][3] = "~";
        mapa[2][4] = "~";
        mapa[2][5] = "~";
        mapa[2][6] = "~";
        mapa[2][7] = "~";
        mapa[2][8] = "~";
        mapa[2][9] = "~";
        mapa[2][10] = "~";
        mapa[3][1] = "~";
        mapa[3][2] = "~";
        mapa[3][3] = "~";
        mapa[3][4] = "~";
        mapa[3][5] = "~";
        mapa[3][6] = "~";
        mapa[3][7] = "~";
        mapa[3][8] = "~";
        mapa[3][9] = "~";
        mapa[3][10] = "~";
        mapa[4][1] = "~";
        mapa[4][2] = "~";
        mapa[4][3] = "~";
        mapa[4][4] = "~";
        mapa[4][5] = "~";
        mapa[4][6] = "~";
        mapa[4][7] = "~";
        mapa[4][8] = "~";
        mapa[4][9] = "~";
        mapa[4][10] = "~";
        mapa[5][1] = "~";
        mapa[5][2] = "~";
        mapa[5][3] = "~";
        mapa[5][4] = "~";
        mapa[5][5] = "~";
        mapa[5][6] = "~";
        mapa[5][7] = "~";
        mapa[5][8] = "~";
        mapa[5][9] = "~";
        mapa[5][10] = "~";
        mapa[6][1] = "~";
        mapa[6][2] = "~";
        mapa[6][3] = "~";
        mapa[6][4] = "~";
        mapa[6][5] = "~";
        mapa[6][6] = "~";
        mapa[6][7] = "~";
        mapa[6][8] = "~";
        mapa[6][9] = "~";
        mapa[6][10] = "~";
        mapa[7][1] = "~";
        mapa[7][2] = "~";
        mapa[7][3] = "~";
        mapa[7][4] = "~";
        mapa[7][5] = "~";
        mapa[7][6] = "~";
        mapa[7][7] = "~";
        mapa[7][8] = "~";
        mapa[7][9] = "~";
        mapa[7][10] = "~";
        mapa[8][1] = "~";
        mapa[8][2] = "~";
        mapa[8][3] = "~";
        mapa[8][4] = "~";
        mapa[8][5] = "~";
        mapa[8][6] = "~";
        mapa[8][7] = "~";
        mapa[8][8] = "~";
        mapa[8][9] = "~";
        mapa[8][10] = "~";
        mapa[9][1] = "~";
        mapa[9][2] = "~";
        mapa[9][3] = "~";
        mapa[9][4] = "~";
        mapa[9][5] = "~";
        mapa[9][6] = "~";
        mapa[9][7] = "~";
        mapa[9][8] = "~";
        mapa[9][9] = "~";
        mapa[9][10] = "~";
        mapa[10][1] = "~";
        mapa[10][2] = "~";
        mapa[10][3] = "~";
        mapa[10][4] = "~";
        mapa[10][5] = "~";
        mapa[10][6] = "~";
        mapa[10][7] = "~";
        mapa[10][8] = "~";
        mapa[10][9] = "~";
        mapa[10][10] = "~";
        for(int l = 0; l < 11; l++){
            for(int c = 0; c < 11; c++) {
                System.out.printf("%s ", mapa[l][c]);
            }
            System.out.println();
        }
    }

    static void mostraMapaTime1(String time1) {
        String[][] mapa = new String[11][11];
        mapa[0][0] = " ";
        //linha
        mapa[0][1] = "A";
        mapa[0][2] = "B";
        mapa[0][3] = "C";
        mapa[0][4] = "D";
        mapa[0][5] = "E";
        mapa[0][6] = "F";
        mapa[0][7] = "G";
        mapa[0][8] = "H";
        mapa[0][9] = "I";
        mapa[0][10] = "J";
        //coluna
        mapa[1][0] = "0";
        mapa[2][0] = "1";
        mapa[3][0] = "2";
        mapa[4][0] = "3";
        mapa[5][0] = "4";
        mapa[6][0] = "5";
        mapa[7][0] = "6";
        mapa[8][0] = "7";
        mapa[9][0] = "8";
        mapa[10][0] = "9";
        //resto
        mapa[1][1] = "~";
        mapa[1][2] = "~";
        mapa[1][3] = "~";
        mapa[1][4] = "~";
        mapa[1][5] = "~";
        mapa[1][6] = "~";
        mapa[1][7] = "~";
        mapa[1][8] = "~";
        mapa[1][9] = "~";
        mapa[1][10] = "~";
        mapa[2][1] = "~";
        mapa[2][2] = "~";
        mapa[2][3] = "~";
        mapa[2][4] = "~";
        mapa[2][5] = "~";
        mapa[2][6] = "~";
        mapa[2][7] = "~";
        mapa[2][8] = "~";
        mapa[2][9] = "~";
        mapa[2][10] = "~";
        mapa[3][1] = "~";
        mapa[3][2] = "~";
        mapa[3][3] = "~";
        mapa[3][4] = "~";
        mapa[3][5] = "~";
        mapa[3][6] = "~";
        mapa[3][7] = "~";
        mapa[3][8] = "~";
        mapa[3][9] = "~";
        mapa[3][10] = "~";
        mapa[4][1] = "~";
        mapa[4][2] = "~";
        mapa[4][3] = "~";
        mapa[4][4] = "~";
        mapa[4][5] = "~";
        mapa[4][6] = "~";
        mapa[4][7] = "~";
        mapa[4][8] = "~";
        mapa[4][9] = "~";
        mapa[4][10] = "~";
        mapa[5][1] = "~";
        mapa[5][2] = "~";
        mapa[5][3] = "~";
        mapa[5][4] = "~";
        mapa[5][5] = "~";
        mapa[5][6] = "~";
        mapa[5][7] = "~";
        mapa[5][8] = "~";
        mapa[5][9] = "~";
        mapa[5][10] = "~";
        mapa[6][1] = "~";
        mapa[6][2] = "~";
        mapa[6][3] = "~";
        mapa[6][4] = "~";
        mapa[6][5] = "~";
        mapa[6][6] = "~";
        mapa[6][7] = "~";
        mapa[6][8] = "~";
        mapa[6][9] = "~";
        mapa[6][10] = "~";
        mapa[7][1] = "~";
        mapa[7][2] = "~";
        mapa[7][3] = "~";
        mapa[7][4] = "~";
        mapa[7][5] = "~";
        mapa[7][6] = "~";
        mapa[7][7] = "~";
        mapa[7][8] = "~";
        mapa[7][9] = "~";
        mapa[7][10] = "~";
        mapa[8][1] = "~";
        mapa[8][2] = "~";
        mapa[8][3] = "~";
        mapa[8][4] = "~";
        mapa[8][5] = "~";
        mapa[8][6] = "~";
        mapa[8][7] = "~";
        mapa[8][8] = "~";
        mapa[8][9] = "~";
        mapa[8][10] = "~";
        mapa[9][1] = "~";
        mapa[9][2] = "~";
        mapa[9][3] = "~";
        mapa[9][4] = "~";
        mapa[9][5] = "~";
        mapa[9][6] = "~";
        mapa[9][7] = "~";
        mapa[9][8] = "~";
        mapa[9][9] = "~";
        mapa[9][10] = "~";
        mapa[10][1] = "~";
        mapa[10][2] = "~";
        mapa[10][3] = "~";
        mapa[10][4] = "~";
        mapa[10][5] = "~";
        mapa[10][6] = "~";
        mapa[10][7] = "~";
        mapa[10][8] = "~";
        mapa[10][9] = "~";
        mapa[10][10] = "~";
        System.out.println(time1);
        for (int l = 0; l < 11; l++) {
            for (int c = 0; c < 11; c++) {
                System.out.printf("%s ", mapa[l][c]);
            }
            System.out.println();
        }
    }
    static void mostraMapaTime2(String time2) {
        String[][] mapa = new String[11][11];
        mapa[0][0] = " ";
        //linha
        mapa[0][1] = "A";
        mapa[0][2] = "B";
        mapa[0][3] = "C";
        mapa[0][4] = "D";
        mapa[0][5] = "E";
        mapa[0][6] = "F";
        mapa[0][7] = "G";
        mapa[0][8] = "H";
        mapa[0][9] = "I";
        mapa[0][10] = "J";
        //coluna
        mapa[1][0] = "0";
        mapa[2][0] = "1";
        mapa[3][0] = "2";
        mapa[4][0] = "3";
        mapa[5][0] = "4";
        mapa[6][0] = "5";
        mapa[7][0] = "6";
        mapa[8][0] = "7";
        mapa[9][0] = "8";
        mapa[10][0] = "9";
        //resto
        mapa[1][1] = "~";
        mapa[1][2] = "~";
        mapa[1][3] = "~";
        mapa[1][4] = "~";
        mapa[1][5] = "~";
        mapa[1][6] = "~";
        mapa[1][7] = "~";
        mapa[1][8] = "~";
        mapa[1][9] = "~";
        mapa[1][10] = "~";
        mapa[2][1] = "~";
        mapa[2][2] = "~";
        mapa[2][3] = "~";
        mapa[2][4] = "~";
        mapa[2][5] = "~";
        mapa[2][6] = "~";
        mapa[2][7] = "~";
        mapa[2][8] = "~";
        mapa[2][9] = "~";
        mapa[2][10] = "~";
        mapa[3][1] = "~";
        mapa[3][2] = "~";
        mapa[3][3] = "~";
        mapa[3][4] = "~";
        mapa[3][5] = "~";
        mapa[3][6] = "~";
        mapa[3][7] = "~";
        mapa[3][8] = "~";
        mapa[3][9] = "~";
        mapa[3][10] = "~";
        mapa[4][1] = "~";
        mapa[4][2] = "~";
        mapa[4][3] = "~";
        mapa[4][4] = "~";
        mapa[4][5] = "~";
        mapa[4][6] = "~";
        mapa[4][7] = "~";
        mapa[4][8] = "~";
        mapa[4][9] = "~";
        mapa[4][10] = "~";
        mapa[5][1] = "~";
        mapa[5][2] = "~";
        mapa[5][3] = "~";
        mapa[5][4] = "~";
        mapa[5][5] = "~";
        mapa[5][6] = "~";
        mapa[5][7] = "~";
        mapa[5][8] = "~";
        mapa[5][9] = "~";
        mapa[5][10] = "~";
        mapa[6][1] = "~";
        mapa[6][2] = "~";
        mapa[6][3] = "~";
        mapa[6][4] = "~";
        mapa[6][5] = "~";
        mapa[6][6] = "~";
        mapa[6][7] = "~";
        mapa[6][8] = "~";
        mapa[6][9] = "~";
        mapa[6][10] = "~";
        mapa[7][1] = "~";
        mapa[7][2] = "~";
        mapa[7][3] = "~";
        mapa[7][4] = "~";
        mapa[7][5] = "~";
        mapa[7][6] = "~";
        mapa[7][7] = "~";
        mapa[7][8] = "~";
        mapa[7][9] = "~";
        mapa[7][10] = "~";
        mapa[8][1] = "~";
        mapa[8][2] = "~";
        mapa[8][3] = "~";
        mapa[8][4] = "~";
        mapa[8][5] = "~";
        mapa[8][6] = "~";
        mapa[8][7] = "~";
        mapa[8][8] = "~";
        mapa[8][9] = "~";
        mapa[8][10] = "~";
        mapa[9][1] = "~";
        mapa[9][2] = "~";
        mapa[9][3] = "~";
        mapa[9][4] = "~";
        mapa[9][5] = "~";
        mapa[9][6] = "~";
        mapa[9][7] = "~";
        mapa[9][8] = "~";
        mapa[9][9] = "~";
        mapa[9][10] = "~";
        mapa[10][1] = "~";
        mapa[10][2] = "~";
        mapa[10][3] = "~";
        mapa[10][4] = "~";
        mapa[10][5] = "~";
        mapa[10][6] = "~";
        mapa[10][7] = "~";
        mapa[10][8] = "~";
        mapa[10][9] = "~";
        mapa[10][10] = "~";
        System.out.println(time2);
        for (int l = 0; l < 11; l++) {
            for (int c = 0; c < 11; c++) {
                System.out.printf("%s ", mapa[l][c]);
            }
            System.out.println();
        }
    }
    static void PortaAvioes(String mapa){

    }

    public static void main(String[] args){
        Scanner ler = new Scanner(System.in);
        System.out.print("Deseja enfrentar o computador ou com outro jogador? Caso queira jogar com o computador clique C e caso outro jogador clique J: ");
        String resposta = ler.next();
        if(resposta.equals("c") || resposta.equals("C")){
            System.out.println("\nVocê possui os seguintes barcos:\n \n1 Porta-aviões(4 espaços);\n2 Encouraçados(3 espaços);\n3 Cruzadores(2 espaços);\n4 Contratorpedeiros(1 espaço).");
            System.out.println("\n Digite um nome para o seu time: ");
            String time1 = ler.next();
            System.out.println("\nEsse é o mapa: \n");
            mostraMapa();
        }
        else if(resposta.equals("j") || resposta.equals("J")){
            System.out.println("\nVocês possuem os seguintes barcos:\n \n1 Porta-aviões(4 espaços);\n2 Encouraçados(3 espaços);\n3 Cruzadores(2 espaços);\n4 Contratorpedeiros(1 espaço).");
            System.out.println("\n Digite um nome para o primeiro time: ");
            String time1 = ler.next();
            System.out.println("\n Digite um nome para o segundo time: ");
            String time2 = ler.next();
            System.out.println("\nEsse é o mapa: \n");
            mostraMapa();
            System.out.println("\nO primeiro a jogar é o "+time1);
            System.out.print("\nEstá pronto? Se sim digite qualquer letra: ");
            String respostaPronto = ler.next();
            System.out.println(" ");
            mostraMapaTime1(time1);
            System.out.println("\nQual barco deseja utilizar?\n \nP - Porta-aviões(4 espaços)(1 unidade);\nE - Encouraçados(3 espaços)(2 unidades);\nC - Cruzadores(2 espaços)(3 unidades);\nT - Contratorpedeiros(1 espaço)(4 unidades).\n");
        }
    }
}
